//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szkola.ViewResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Szkola.ViewResources.GlobalResources", typeof(GlobalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Ciemny.
        /// </summary>
        public static string Ciemny {
            get {
                return ResourceManager.GetString("Ciemny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Dodaj klase.
        /// </summary>
        public static string DodajKlase {
            get {
                return ResourceManager.GetString("DodajKlase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Dodaj ogłoszenie.
        /// </summary>
        public static string DodajOgloszenie {
            get {
                return ResourceManager.GetString("DodajOgloszenie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Dodaj plan lekcji.
        /// </summary>
        public static string DodajPlanLekcji {
            get {
                return ResourceManager.GetString("DodajPlanLekcji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Dodaj użytkownika.
        /// </summary>
        public static string DodajUzytkownika {
            get {
                return ResourceManager.GetString("DodajUzytkownika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Jasny.
        /// </summary>
        public static string Jasny {
            get {
                return ResourceManager.GetString("Jasny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Klasa.
        /// </summary>
        public static string Klasa {
            get {
                return ResourceManager.GetString("Klasa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Motyw.
        /// </summary>
        public static string Motyw {
            get {
                return ResourceManager.GetString("Motyw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Ogłoszenia.
        /// </summary>
        public static string Ogloszenia {
            get {
                return ResourceManager.GetString("Ogloszenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Plan lekcji.
        /// </summary>
        public static string PlanLekcji {
            get {
                return ResourceManager.GetString("PlanLekcji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Plik.
        /// </summary>
        public static string Plik {
            get {
                return ResourceManager.GetString("Plik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Użytkownik.
        /// </summary>
        public static string Uzytkownik {
            get {
                return ResourceManager.GetString("Uzytkownik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Widok.
        /// </summary>
        public static string Widok {
            get {
                return ResourceManager.GetString("Widok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Wyświetl wszystkich użytkowników.
        /// </summary>
        public static string WszyscyUzytkownicy {
            get {
                return ResourceManager.GetString("WszyscyUzytkownicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Wyświetl wszystkie klasy.
        /// </summary>
        public static string WszystkieKlasy {
            get {
                return ResourceManager.GetString("WszystkieKlasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Wyświetl wszystkie ogłoszenia.
        /// </summary>
        public static string WszystkieOgloszenia {
            get {
                return ResourceManager.GetString("WszystkieOgloszenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Wyświetl wszystkie plany lekcji.
        /// </summary>
        public static string WszystkiePlanyLekcji {
            get {
                return ResourceManager.GetString("WszystkiePlanyLekcji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Zamknij.
        /// </summary>
        public static string Zamknij {
            get {
                return ResourceManager.GetString("Zamknij", resourceCulture);
            }
        }
    }
}
